import "./globals.css";
import Provider from "./components/context/Provider";
import { auth } from "./lib/auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth()

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
         <Provider>
          {children}
          { session && session ? <></> : <></>}
         </Provider>
      </body>
    </html>
  );
}
